/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check API health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List assets */
        get: operations["listAssets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/technicians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List technicians */
        get: operations["listTechnicians"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work-orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List work orders
         * @description Optionally filter work orders by state and/or priority.
         */
        get: operations["listWorkOrders"];
        put?: never;
        /** Report a new work order */
        post: operations["createWorkOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work-orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a work order by id */
        get: operations["getWorkOrder"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work-orders/{id}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign a technician to a work order */
        post: operations["assignWorkOrderTechnician"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/work-orders/{id}/transitions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transition a work order to its next lifecycle state */
        post: operations["transitionWorkOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregate dashboard summary */
        get: operations["getDashboardSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Current stage of a work order in its lifecycle. Transitions are driven by WorkOrderAction commands.
         * @enum {string}
         */
        WorkOrderState: "reported" | "triaged" | "scheduled" | "in_progress" | "completed" | "cancelled";
        /**
         * @description Command used to transition a work order from one state to another.
         * @enum {string}
         */
        WorkOrderAction: "triage" | "schedule" | "start" | "complete" | "cancel";
        /**
         * @description Urgency level assigned to a work order.
         * @enum {string}
         */
        Priority: "low" | "medium" | "high" | "critical";
        /** @description A piece of equipment that can be the subject of a work order. */
        Asset: {
            /**
             * Format: uuid
             * @description Unique identifier of the asset.
             */
            id: string;
            /** @description Human-readable asset tag printed on the physical equipment. */
            tag: string;
            /** @description Descriptive name of the asset. */
            name: string;
            /** @description Physical location of the asset (e.g. building, room, line). */
            location: string;
        };
        /** @description A maintenance technician who can be assigned to work orders. */
        Technician: {
            /**
             * Format: uuid
             * @description Unique identifier of the technician.
             */
            id: string;
            /** @description Full name of the technician. */
            name: string;
            /** @description Primary area of expertise (e.g. electrical, mechanical, HVAC). */
            specialty: string;
        };
        /** @description A maintenance task tracked from report to completion. */
        WorkOrder: {
            /**
             * Format: uuid
             * @description Unique identifier of the work order.
             */
            id: string;
            /** @description Human-readable reference code (e.g. WO-2026-00042). */
            reference: string;
            /**
             * Format: uuid
             * @description Identifier of the asset this work order applies to.
             */
            assetId: string;
            /** @description Short summary of the maintenance task. */
            title: string;
            /** @description Detailed description of the issue or task. */
            description: string;
            priority: components["schemas"]["Priority"];
            state: components["schemas"]["WorkOrderState"];
            /**
             * Format: uuid
             * @description Identifier of the technician assigned to this work order, if any.
             */
            technicianId: string | null;
            /**
             * Format: date-time
             * @description Timestamp when the work order was first reported.
             */
            reportedAt: string;
            /**
             * Format: date-time
             * @description Timestamp when the work order was last updated.
             */
            updatedAt: string;
        };
        /** @description Payload for reporting a new work order. */
        NewWorkOrder: {
            /**
             * Format: uuid
             * @description Identifier of the asset this work order applies to.
             */
            assetId: string;
            /** @description Short summary of the maintenance task. */
            title: string;
            /** @description Detailed description of the issue or task. */
            description: string;
            priority: components["schemas"]["Priority"];
        };
        /** @description Command to move a work order to its next lifecycle state. */
        TransitionCommand: {
            action: components["schemas"]["WorkOrderAction"];
        };
        /** @description Command to assign a technician to a work order. */
        AssignmentCommand: {
            /**
             * Format: uuid
             * @description Identifier of the technician to assign.
             */
            technicianId: string;
        };
        /** @description Aggregate counts of work orders for the operations dashboard. */
        DashboardSummary: {
            /** @description Total number of work orders not yet completed or cancelled. */
            totalOpen: number;
            /** @description Number of open work orders with critical priority. */
            criticalOpen: number;
            /** @description Number of open work orders with no technician assigned. */
            unassigned: number;
            /** @description Count of work orders grouped by state. */
            byState: {
                [key: string]: number;
            };
        };
        /** @description Standard error response shape. */
        ApiError: {
            /** @description Human-readable error message. */
            message: string;
            /** @description Optional additional error context. */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The API is healthy. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok: boolean;
                    };
                };
            };
        };
    };
    listAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of assets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Asset"][];
                };
            };
        };
    };
    listTechnicians: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of technicians. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Technician"][];
                };
            };
        };
    };
    listWorkOrders: {
        parameters: {
            query?: {
                /** @description Filter results to work orders in this state. */
                state?: components["schemas"]["WorkOrderState"];
                /** @description Filter results to work orders with this priority. */
                priority?: components["schemas"]["Priority"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of work orders matching the filters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"][];
                };
            };
            /** @description An invalid state or priority filter was supplied. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    createWorkOrder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewWorkOrder"];
            };
        };
        responses: {
            /** @description The work order was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            /** @description The referenced asset does not exist or the payload is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getWorkOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the work order. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The requested work order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            /** @description No work order exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    assignWorkOrderTechnician: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the work order. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCommand"];
            };
        };
        responses: {
            /** @description The technician was assigned to the work order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            /** @description The work order or technician does not exist. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description Assignment is not allowed because the work order is in a final state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    transitionWorkOrder: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier of the work order. */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransitionCommand"];
            };
        };
        responses: {
            /** @description The work order was transitioned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkOrder"];
                };
            };
            /** @description The requested action is invalid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description No work order exists with the given id. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /** @description The requested action is not a legal transition from the work order's current state. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    getDashboardSummary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregate work order counts for the operations dashboard. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
}
